import type { Metadata } from "next";
import Link from "next/link";
import { paperTextureDataUri } from "@/lib/paper-texture";

const CONTACT_EMAIL = "support@glowingstar.ai";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms governing the use of glowingstar.ai.",
};

const sections = [
  {
    heading: "About these terms",
    body: [
      "These terms govern your use of glowingstar.ai, operated by GlowingStar, Inc. By using this website you agree to these terms. Institutional deployments of our learning platform are governed by separate written agreements with partner schools and universities, which take precedence over these website terms.",
    ],
  },
  {
    heading: "Use of the site",
    body: [
      "You may browse this site and the product experiences it links to for personal, educational, and evaluation purposes. You agree not to misuse the site — including attempting to disrupt the service, probe systems you are not authorized to access, or use automated means to extract data at scale.",
    ],
  },
  {
    heading: "Content and intellectual property",
    body: [
      "The content, design, and software on this site belong to GlowingStar, Inc. or its licensors. University and institution marks shown on this site identify where our team members studied or worked and do not imply endorsement by those institutions.",
    ],
  },
  {
    heading: "AI-generated content",
    body: [
      "Our product experiences include content generated by AI systems. AI-generated explanations can be incorrect; that is, in part, why our platform measures learning outcomes rather than assuming them. Product experiences on this site are demonstrations and are not a substitute for professional educational advice.",
    ],
  },
  {
    heading: "Disclaimer and limitation of liability",
    body: [
      "This site is provided “as is” without warranties of any kind, express or implied. To the maximum extent permitted by law, GlowingStar, Inc. is not liable for indirect, incidental, or consequential damages arising from use of this site.",
    ],
  },
  {
    heading: "Contact",
    body: [
      `Questions about these terms? Email ${CONTACT_EMAIL}. These terms are effective as of June 10, 2026.`,
    ],
  },
];

export default function TermsPage(): JSX.Element {
  return (
    <div className="relative min-h-screen overflow-x-hidden bg-[#ede6d9] text-[#17120f]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.92),transparent_54%),linear-gradient(180deg,#f5efe3_0%,#ece2d2_48%,#e7ddce_100%)]" />
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 opacity-55"
        style={{
          backgroundImage: paperTextureDataUri,
          backgroundRepeat: "repeat",
          backgroundSize: "240px 240px",
        }}
      />
      <main className="relative mx-auto w-full max-w-3xl px-6 py-20 sm:px-10">
        <Link
          href="/"
          className="text-sm text-[#17120f]/55 underline decoration-[#17120f]/25 underline-offset-4 hover:text-[#17120f]"
        >
          ← Back to home
        </Link>
        <h1 className="mt-6 font-heading text-3xl sm:text-4xl">
          Terms of Service
        </h1>
        <p className="mt-3 text-sm text-[#17120f]/55">
          Effective June 10, 2026
        </p>
        <div className="mt-10 space-y-8">
          {sections.map((section) => (
            <section key={section.heading}>
              <h2 className="font-heading text-xl text-[#17120f]">
                {section.heading}
              </h2>
              {section.body.map((paragraph) => (
                <p
                  key={paragraph.slice(0, 40)}
                  className="mt-3 text-base leading-8 text-[#17120f]/72"
                >
                  {paragraph}
                </p>
              ))}
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
